# https://openapi-generator.tech/docs/generators/java/
validateSpec: false
additionalProperties:
  artifactId: sentry-api-client-java
  apiPackage: com.sentry.api.client.java
  allowUnicodeIdentifiers: true
  serializableModel: true
  dateLibrary: java8
