# https://openapi-generator.tech/docs/generators/java/
additionalProperties:
  apiPackage: com.sentry.api.client.api
  artifactId: sentry-api-client-java
  groupId: com.sentry
  invokerPackage: com.sentry.api.client
  library: jersey3
  modelPackage: com.sentry.api.client.model
